export const FIGURES = [
    {
        id: "3-1",
        imageName: "image1.png",
        caption: "图3-1 系统分层架构图",
        section: "系统总体设计",
        headline: "可信溯源分层架构",
        subhead: "从感知采集到链上存证形成统一闭环",
        size: { width: 2200, height: 1500 },
        renderer: "systemLayers",
    },
    {
        id: "3-2",
        imageName: "image2.png",
        caption: "图3-2 系统端到端数据流图",
        section: "系统总体设计",
        headline: "端到端数据流",
        subhead: "采集、验签、评分、锚定与公开查询一体贯通",
        size: { width: 2200, height: 1480 },
        renderer: "dataFlow",
    },
    {
        id: "3-3",
        imageName: "image3.png",
        caption: "图3-3 核心数据表ER关系图",
        section: "数据模型设计",
        headline: "核心数据实体关系",
        subhead: "围绕事件主线连接请求、评分、提交与回执",
        size: { width: 1600, height: 920 },
        renderer: "coreEr",
    },
    {
        id: "3-4",
        imageName: "image4.png",
        caption: "图3-4 IngestStatus状态机图",
        section: "数据模型设计",
        headline: "IngestStatus 生命周期",
        subhead: "锚定流程在成功、重试与死信之间保持可追踪状态",
        size: { width: 2200, height: 1450 },
        renderer: "statusMachine",
    },
    {
        id: "3-5",
        imageName: "image5.png",
        caption: "图3-5 系统安全架构图",
        section: "系统安全架构",
        headline: "设备到应用的安全防线",
        subhead: "身份、权限、验签、审计与存证逐层收口",
        size: { width: 1600, height: 920 },
        renderer: "securityArchitecture",
    },
    {
        id: "4-1",
        imageName: "image6.png",
        caption: "图4-1 STM32H743最小系统原理图",
        section: "硬件实现",
        headline: "STM32H743 最小系统",
        subhead: "主控、时钟、复位、调试与供电构成基础运行单元",
        size: { width: 1600, height: 920 },
        renderer: "stm32Minimal",
    },
    {
        id: "4-2",
        imageName: "image7.png",
        caption: "图4-2 多传感器接口与总线连接图",
        section: "硬件实现",
        headline: "多传感器与总线连接",
        subhead: "I2C、UART 与 SPI 协同接入环境感知与无线通信模块",
        size: { width: 1600, height: 920 },
        renderer: "sensorBuses",
    },
    {
        id: "4-3",
        imageName: "image8.png",
        caption: "图4-3 ATECC608A连接与签名流程图",
        section: "硬件实现",
        headline: "安全芯片连接与签名链路",
        subhead: "原始采样在设备侧完成不可导出的硬件签名",
        size: { width: 1600, height: 920 },
        renderer: "secureElementSigning",
    },
    {
        id: "4-4",
        imageName: "image9.png",
        caption: "图4-4 Wi-Fi/LoRa通信组网图",
        section: "硬件实现",
        headline: "Wi-Fi / LoRa 双通道组网",
        subhead: "冷库、运输与果园场景共享同一上云入口",
        size: { width: 1600, height: 920 },
        renderer: "networkTopology",
    },
    {
        id: "4-5",
        imageName: "image10.png",
        caption: "图4-5 电源管理原理图",
        section: "硬件实现",
        headline: "电源管理路径",
        subhead: "输入保护、稳压分配与模拟数字隔离保持系统稳定",
        size: { width: 1600, height: 920 },
        renderer: "powerManagement",
    },
    {
        id: "5-1",
        imageName: "image11.png",
        caption: "图5-1 FreeRTOS任务调度与数据通路图",
        section: "软件实现",
        headline: "FreeRTOS 任务与队列",
        subhead: "采样、签名、评分与通信在实时调度下解耦执行",
        size: { width: 1600, height: 920 },
        renderer: "freertosPipeline",
    },
    {
        id: "5-2",
        imageName: "image12.png",
        caption: "图5-2 哈希规范化流程图",
        section: "软件实现",
        headline: "哈希规范化流程",
        subhead: "跨语言保持一致的 canonical_hash 生成规则",
        size: { width: 2200, height: 1480 },
        renderer: "hashCanonicalization",
    },
    {
        id: "5-3",
        imageName: "image13.png",
        caption: "图5-3 双层幂等处理时序图",
        section: "软件实现",
        headline: "双层幂等处理",
        subhead: "同时兜住重放请求与重复内容写入",
        size: { width: 2200, height: 1480 },
        renderer: "idempotencySequence",
    },
    {
        id: "5-4",
        imageName: "image14.png",
        caption: "图5-4 签名验证流程图",
        section: "软件实现",
        headline: "签名验证服务流程",
        subhead: "解析信封、复建消息、验签落库只保留可信数据",
        size: { width: 1600, height: 920 },
        renderer: "signatureVerification",
    },
    {
        id: "5-5",
        imageName: "image15.png",
        caption: "图5-5 区块链锚定引擎工作时序图",
        section: "软件实现",
        headline: "区块链锚定引擎时序",
        subhead: "提交、轮询确认与失败恢复围绕同一状态机推进",
        size: { width: 2200, height: 1480 },
        renderer: "anchorSequence",
    },
    {
        id: "5-6",
        imageName: "image16.png",
        caption: "图5-6 四阶段Rollout策略图",
        section: "软件实现",
        headline: "四阶段上线策略",
        subhead: "从保守验证到全量切换，每一步都有回退闸门",
        size: { width: 1600, height: 920 },
        renderer: "rolloutStrategy",
    },
    {
        id: "5-7",
        imageName: "image17.png",
        caption: "图5-7 前端页面结构与关键界面示意图",
        section: "软件实现",
        headline: "前端页面结构",
        subhead: "Dashboard、公开溯源与管理后台共用一套清晰信息架构",
        size: { width: 1600, height: 920 },
        renderer: "frontendStructure",
    },
    {
        id: "6-1",
        imageName: "image18.png",
        caption: "图6-1 硬件测试平台实物图",
        section: "系统测试",
        headline: "硬件测试平台",
        subhead: "传感节点、校准源与上位机构成统一测试工位",
        size: { width: 1600, height: 920 },
        renderer: "hardwareTestRig",
    },
    {
        id: "6-2",
        imageName: "image19.png",
        caption: "图6-2 端到端溯源链路验证截图",
        section: "系统测试",
        headline: "端到端溯源验证",
        subhead: "从设备上报到公开查询的全链路结果在同一视图中闭环展示",
        size: { width: 1600, height: 920 },
        renderer: "e2eValidation",
    },
    {
        id: "6-3",
        imageName: "image20.png",
        caption: "图6-3 Canary监控与自动回滚结果图",
        section: "系统测试",
        headline: "Canary 监控与自动回滚",
        subhead: "以实时指标判断风险，并在阈值触发时即时回退",
        size: { width: 1600, height: 920 },
        renderer: "canaryRollback",
    },
];

export function getFigureByImageName(imageName) {
    return FIGURES.find((figure) => figure.imageName === imageName);
}
